### ISSUE TITLE
是否做支持vue3的k线

### ISSUE THREAD

**Issue by lotherli** [zhaitianye/jingtumzs_kline#1]
是否做支持vue3的k线

**Comment by zhaitianye** [comment]
支持，这个项目是fork别的项目修改而来的。之后会有颜色等方面的修改。不建议直接使用。建议fork源码，自建npm包使用。

**Comment by lotherli** [comment]
这个项目是否重构为最新的？

**Comment by zhaitianye** [comment]
目前是的，基于 v0.2.8 版本。真实项目地址：  https://www.chainscan.pro/#/order/index  可以做参考
